name: Deploy companyprofile App

on:
   push:
      branches:
         - main # Change to your specific branch
         # - deployprod  # Additional branch for deployment

jobs:
   deploy:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout repository
           uses: actions/checkout@v4

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: "20"

         - name: Check Node.js version
           run: node -v

         - name: Set up SSH
           uses: webfactory/ssh-agent@v0.5.1
           with:
              ssh-private-key: ${{ secrets.INTL2_PRIVATE_KEY }}

         - name: Deploy to DigitalOcean
           env:
              HOST: 128.199.74.46
              USERNAME: root
              TARGET_DIR: /var/www/intl2-companyprofile-v02
              APP_NAME: companyprofile #should match the name of the server block
              PORT: 3000

           run: |
              ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << EOF
                export PATH=/root/.nvm/versions/node/v22.12.0/bin:$PATH #'which pm2' command on terminal will give the right path
                cd $TARGET_DIR
                git pull origin ${GITHUB_REF#refs/heads/}
                npm install
                npm run build
                if pm2 list | grep -q $APP_NAME; then
                  echo "Restarting application: $APP_NAME"
                  pm2 restart $APP_NAME
                else
                  echo "Starting application: $APP_NAME"
                  pm2 start npm --name $APP_NAME -- start -- --port=$PORT
                fi            
                pm2 save
              EOF
